# Generated by Django 5.2.7 on 2025-11-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelversion_species_inference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inference',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='modelversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
    ]
